server {
    listen 5173;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy para o backend
    location /api/ {
        proxy_pass http://hackgov-backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA fallback (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}