package com.fiap.hackgov.bidding.internal.entities.enums;

public enum ProcessStage {
    CADASTRO_REQUISICAO,
    HOMOLOGACAO_SECRETARIO,
    RECEBIMENTO_COMPRAS,
    ANALISE_REQUISICAO,
    HOMOLOGACAO_COMPRAS,
    COMPOSICAO_PROCESSO,
    PROCESSO_LICITATORIO,
    ASSINATURA_CONTRATO,
    INICIO_SERVICOS,
    EMISSAO_EMPENHO,
    DECLARACAO_PAGAMENTO,
    EXECUCAO_PAGAMENTO,
    PRESTACAO_CONTAS,
    ANALISE_PRESTACAO,
    HOMOLOGACAO_PRESTACAO
}
