package com.fiap.hackgov.tools.internal.services;
import com.fiap.hackgov.auth.internal.entities.enums.Roles;import com.fiap.hackgov.cityhall_management.internal.entities.Employee;import com.fiap.hackgov.shared.infra.exceptions.*;import com.fiap.hackgov.tools.internal.entities.*;import com.fiap.hackgov.tools.internal.repositories.*;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service @RequiredArgsConstructor public class ToolConfigurationService{
 private final ToolConfigurationRepository repository;private final UserToolFavoriteRepository favoriteRepository;private final ToolPermissionService permissionService;
 private static final List<Seed> SEEDS=List.of(new Seed("cargos","Cargos","Gestao","bi-person-badge-fill","Cadastro de cargos.","/cargos",true),new Seed("setores","Setores","Gestao","bi-building-gear","Estrutura administrativa.","/setores",true),new Seed("gestao","Gestao","Gestao","bi-graph-up-arrow","Indicadores operacionais.","/gestao",true),new Seed("tarefas","Tarefas","Gestao","bi-check2-square","Tarefas e demandas.","/tarefas",true),new Seed("agenda","Agenda","Gestao","bi-calendar3","Eventos e prazos.","/agenda",true),new Seed("compras-licitacoes","Compras e Licitacoes","Processos","bi-bag-check-fill","Processos de compras.","/processos",true),new Seed("caixa-entrada","Caixa de Entrada","Usuarios","bi-inbox-fill","Entradas pessoais e setoriais.","/caixa-entrada",true),new Seed("documentos","Documentos","Dados","bi-folder2-open","Acervo municipal.","/documentos",true),new Seed("clientes-gerais","Clientes Gerais","Atendimento","bi-person-vcard-fill","Cadastro municipal.","/clientes",false),new Seed("patrulha-agricola","Patrulha Agricola","Atendimento","bi-tractor","Servicos rurais.","/patrulha-agricola",false),new Seed("funcionarios","Funcionarios","Usuarios","bi-people-fill","Gestao de servidores.","/funcionarios",true),new Seed("controle-acesso","Controle de Acesso","Usuarios","bi-shield-lock-fill","Permissoes por perfil.","/controle-acesso",true),new Seed("auditoria","Auditoria","Dados","bi-shield-check","Trilha de alteracoes.","/auditoria",true),new Seed("importacao-dados","Importacao de Dados","Dados","bi-cloud-arrow-up-fill","Importacao de planilhas.",null,false));
 @Transactional public List<Response> list(Employee employee){Employee current=require(employee);ensure(current);Set<String> favorites=favoriteRepository.findByEmployee_Id(current.getId()).stream().map(UserToolFavorite::getToolSlug).collect(java.util.stream.Collectors.toSet());return repository.findByCityHall_IdOrderByCategoryAscNameAsc(city(current)).stream().filter(item->Roles.ADMIN.equals(current.getRole())||((item.isEnabled()||item.isMandatory())&&(!item.isRestricted()||permissionService.canAccess(item.getSlug(),current)))).map(item->response(item,favorites.contains(item.getSlug()))).toList();}
 @Transactional public Response update(String slug,Update request,Employee employee){Employee current=admin(employee);ensure(current);ToolConfiguration item=repository.findByCityHall_IdAndSlug(city(current),slug).orElseThrow(()->new ResourceNotFoundException("Ferramenta nao encontrada"));if(item.isMandatory()&&!request.enabled())throw new BusinessException("Ferramentas obrigatorias nao podem ser desativadas");item.setEnabled(item.isMandatory()||request.enabled());item.setRestricted(request.restricted());return response(repository.save(item),favoriteRepository.findByEmployee_IdAndToolSlug(current.getId(),slug).isPresent());}
 @Transactional public Favorite favorite(String slug,Employee employee){Employee current=require(employee);ensure(current);ToolConfiguration tool=repository.findByCityHall_IdAndSlug(city(current),slug).filter(item->item.isEnabled()||item.isMandatory()).orElseThrow(()->new BusinessException("Ferramenta indisponivel"));Optional<UserToolFavorite> found=favoriteRepository.findByEmployee_IdAndToolSlug(current.getId(),slug);if(found.isPresent()){favoriteRepository.delete(found.get());return new Favorite(slug,false);}UserToolFavorite value=new UserToolFavorite();value.setEmployee(current);value.setToolSlug(tool.getSlug());favoriteRepository.save(value);return new Favorite(slug,true);}
 private void ensure(Employee employee){if(!repository.findByCityHall_IdOrderByCategoryAscNameAsc(city(employee)).isEmpty())return;for(Seed seed:SEEDS){ToolConfiguration item=new ToolConfiguration();item.setCityHall(employee.getCityHallId());item.setSlug(seed.slug);item.setName(seed.name);item.setCategory(seed.category);item.setIcon(seed.icon);item.setDescription(seed.description);item.setRoute(seed.route);item.setMandatory(seed.mandatory);item.setEnabled(seed.mandatory||!seed.slug.equals("importacao-dados"));repository.save(item);}}
 private Employee require(Employee e){if(e==null)throw new UnauthorizedException("E necessario estar autenticado");city(e);return e;}private Employee admin(Employee e){e=require(e);if(!Roles.ADMIN.equals(e.getRole()))throw new UnauthorizedException("Somente administradores podem configurar ferramentas");return e;}private UUID city(Employee e){if(e.getCityHallId()==null)throw new BusinessException("Usuario sem prefeitura");return e.getCityHallId().getId();}
 private Response response(ToolConfiguration i,boolean favorite){String route=i.getRoute()==null&&"importacao-dados".equals(i.getSlug())?"/importacao":i.getRoute();return new Response(i.getSlug(),i.getName(),i.getCategory(),i.getIcon(),i.getDescription(),route,i.isMandatory(),i.isEnabled(),i.isRestricted(),favorite);}private record Seed(String slug,String name,String category,String icon,String description,String route,boolean mandatory){}public record Update(boolean enabled,boolean restricted){}public record Favorite(String slug,boolean favorite){}public record Response(String id,String name,String category,String icon,String description,String route,boolean mandatory,boolean enabled,boolean restricted,boolean favorite){}
}
