import { useEffect, useState } from "react";
import { DashboardLayout } from "../components/DashboardLayout.jsx";
import { PageHeader } from "../components/DashboardShared.jsx";
import { api } from "../services/api.js";

const fields={departments:[["nome","Nome *"],["descricao","Descricao"],["ativo","Ativo"]],employees:[["nome","Nome *"],["email","E-mail *"],["cpf","CPF"],["numero_de_registro","Matricula"],["setor","Setor"],["cargo","Cargo"],["carga_horaria","Carga horaria"],["salario","Salario"],["admissao","Admissao"]]};
const labels={UPLOADED:"Enviado",VALIDATED:"Validado",VALIDATION_FAILED:"Validacao com falhas",IMPORTED:"Importado",IMPORT_FAILED:"Importado com falhas"};

export default function SpreadsheetImportPage(){
 const[target,setTarget]=useState("departments"),[file,setFile]=useState(null),[preview,setPreview]=useState(null),[mapping,setMapping]=useState({}),[mode,setMode]=useState("UPSERT"),[report,setReport]=useState(null),[history,setHistory]=useState([]),[message,setMessage]=useState(null),[busy,setBusy]=useState(false);
 async function loadHistory(){try{setHistory(await api.getImportHistory());}catch{setHistory([]);}}
 useEffect(()=>{loadHistory();},[]);
 async function upload(event){event.preventDefault();setBusy(true);try{const result=await api.previewImport(target,file);setPreview(result);setMapping(result.suggestedMapping||{});setReport(null);setMessage(null);}catch(error){setMessage({type:"danger",text:error.message});}finally{setBusy(false);}}
 async function validate(){setBusy(true);try{const result=await api.validateImport(preview.id,{mode,mapping});setReport(result);setMessage({type:result.invalidRows?"warning":"success",text:result.invalidRows?"Corrija o mapeamento ou os dados indicados.":"Planilha validada e pronta para importar."});await loadHistory();}catch(error){setMessage({type:"danger",text:error.message});}finally{setBusy(false);}}
 async function execute(){setBusy(true);try{const result=await api.executeImport(preview.id);setMessage({type:result.failedRows?"warning":"success",text:`Importacao concluida: ${result.createdRecords} criados, ${result.updatedRecords} atualizados e ${result.failedRows} falhas.`});setPreview(null);setReport(null);setFile(null);await loadHistory();}catch(error){setMessage({type:"danger",text:error.message});}finally{setBusy(false);}}
 return <DashboardLayout styles={["/css/spreadsheet-import.css"]}><main className="dashboard"><div className="container"><PageHeader eyebrow="Carga assistida e auditavel" title="Importacao de Dados" />{message&&<div className={`auth-message ${message.type} mb-3`}>{message.text}</div>}
 {!preview&&<form className="panel import-upload" onSubmit={upload}><div><label className="field-label">Destino</label><select className="field-input" value={target} onChange={e=>setTarget(e.target.value)}><option value="departments">Setores</option><option value="employees">Servidores</option></select></div><div><label className="field-label">Arquivo CSV ou XLSX (ate 5 MB)</label><input className="field-input" type="file" accept=".csv,.xlsx" required onChange={e=>setFile(e.target.files[0])}/></div><button className="btn btn-primary" disabled={busy}>{busy?"Lendo...":"Gerar preview"}</button></form>}
 {preview&&<><section className="panel"><div className="d-flex justify-content-between gap-2"><div><p className="eyebrow dark mb-1">Preview</p><h3>{preview.filename}</h3><small>{preview.totalRows} linhas · {preview.ignoredRows} vazias ignoradas</small></div><button className="btn btn-outline-secondary" onClick={()=>{setPreview(null);setReport(null);}}>Trocar arquivo</button></div><div className="table-responsive mt-3"><table className="table"><thead><tr>{preview.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{preview.previewRows.map(row=><tr key={row.number}>{row.values.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div></section>
 <section className="panel mt-3"><h3>Mapeamento</h3><div className="import-mapping">{fields[target].map(([key,label])=><div key={key}><label className="field-label">{label}</label><select className="field-input" value={mapping[key]||""} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="">Nao importar</option>{preview.headers.map(h=><option key={h}>{h}</option>)}</select></div>)}</div><div className="d-flex gap-2 align-items-end mt-3"><div><label className="field-label">Modo</label><select className="field-input" value={mode} onChange={e=>setMode(e.target.value)}><option value="CREATE">Criar apenas</option><option value="UPDATE">Atualizar existentes</option><option value="UPSERT">Criar ou atualizar</option></select></div><button className="btn btn-primary" disabled={busy} onClick={validate}>Validar dados</button>{report?.invalidRows===0&&<button className="btn btn-success" disabled={busy} onClick={execute}>Executar importacao</button>}</div></section>
 {report&&<section className="panel mt-3"><h3>Relatorio de qualidade</h3><div className="import-stats"><strong>{report.validRows} validas</strong><strong>{report.invalidRows} invalidas</strong><strong>{report.duplicatedRows} duplicadas</strong></div>{report.errors.length>0&&<div className="table-responsive"><table className="table"><thead><tr><th>Linha</th><th>Campo</th><th>Valor</th><th>Erro</th></tr></thead><tbody>{report.errors.slice(0,100).map((e,i)=><tr key={i}><td>{e.rowNumber||"-"}</td><td>{e.field}</td><td>{e.value}</td><td>{e.message}</td></tr>)}</tbody></table></div>}</section>}</>}
 <section className="panel mt-3"><h3>Historico</h3><div className="table-responsive"><table className="table"><thead><tr><th>Arquivo</th><th>Destino</th><th>Modo</th><th>Status</th><th>Resultado</th><th>Data</th></tr></thead><tbody>{history.map(item=><tr key={item.id}><td>{item.filename}</td><td>{item.target}</td><td>{item.mode||"-"}</td><td>{labels[item.status]}</td><td>{item.createdRecords} criados / {item.updatedRecords} atualizados / {item.failedRows} falhas</td><td>{new Date(item.createdAt).toLocaleString("pt-BR")}</td></tr>)}</tbody></table></div></section>
 </div></main></DashboardLayout>;
}
