package com.fiap.hackgov.tasks.internal.services;
import com.fiap.hackgov.auth.internal.entities.enums.Roles;
import com.fiap.hackgov.cityhall_management.internal.entities.*;
import com.fiap.hackgov.cityhall_management.internal.repositories.SectorRepository;
import com.fiap.hackgov.inbox.internal.services.InboxService;
import com.fiap.hackgov.shared.infra.exceptions.*;
import com.fiap.hackgov.tasks.internal.DTOs.CrossSectorRequestDTOs.*;
import com.fiap.hackgov.tasks.internal.entities.*;
import com.fiap.hackgov.tasks.internal.repositories.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;import java.util.*;

@Service @RequiredArgsConstructor
public class CrossSectorTaskRequestService {
 private final CrossSectorTaskRequestRepository repository;private final SectorRepository sectorRepository;private final BoardRepository boardRepository;private final TaskReporitory taskRepository;private final InboxService inboxService;
 @Transactional public Response create(Create dto,Employee employee){Employee current=require(employee);Sector origin=sector(current);Sector destination=sectorRepository.findByIdAndCityHall_Id(dto.destinationSectorId(),city(current)).orElseThrow(()->new BusinessException("Setor de destino invalido"));if(origin.getId().equals(destination.getId()))throw new BusinessException("A demanda precisa ser enviada para outro setor");CrossSectorTaskRequest item=new CrossSectorTaskRequest();item.setCityHall(current.getCityHallId());item.setOriginSector(origin);item.setDestinationSector(destination);item.setTitle(dto.title().trim());item.setDescription(dto.description()==null?"":dto.description().trim());item.setPriority(dto.priority()==null?Task.Priority.NORMAL:dto.priority());item.setDeadline(dto.deadline());item.setRequestedBy(current);item=repository.save(item);inboxService.notifyCrossSectorRequest(item);return response(item);}
 @Transactional(readOnly=true) public List<Response> list(Employee employee){Employee current=require(employee);return repository.findByCityHall_IdOrderByCreatedAtDesc(city(current)).stream().filter(item->Roles.ADMIN.equals(current.getRole())||item.getOriginSector().getId().equals(sector(current).getId())||item.getDestinationSector().getId().equals(sector(current).getId())).map(this::response).toList();}
 @Transactional public Response accept(UUID id,Answer answer,Employee employee){Employee current=require(employee);CrossSectorTaskRequest item=pending(id,current);requireDestination(item,current);Board board=boardRepository.findFirstByCityHall_IdAndSector_Id(city(current),item.getDestinationSector().getId()).orElseGet(()->{Board value=new Board();value.setName(item.getDestinationSector().getName());value.setCityHall(current.getCityHallId());value.setSector(item.getDestinationSector());return boardRepository.save(value);});Task task=new Task();task.setTitle(item.getTitle());task.setDescription(item.getDescription());task.setPriority(item.getPriority());task.setStatus(Task.Status.IN_PROGRESS);task.setStartDate(LocalDateTime.now());task.setEndDate(item.getDeadline()==null?null:item.getDeadline().atTime(23,59));task.setBoard(board);task.setResponsible(current);task.setResponsibles(new LinkedHashSet<>(Set.of(current)));task.setCreatedBy(item.getRequestedBy());task=taskRepository.save(task);item.setGeneratedTask(task);finish(item,current,answer.feedback(),CrossSectorTaskRequest.Status.ACCEPTED);inboxService.completeObject(city(current),"cross_sector_task_request",item.getId());inboxService.notifyRequestResult(item,"aceita");return response(item);}
 @Transactional public Response reject(UUID id,Answer answer,Employee employee){Employee current=require(employee);CrossSectorTaskRequest item=pending(id,current);requireDestination(item,current);if(answer.feedback()==null||answer.feedback().isBlank())throw new BusinessException("Informe o motivo da recusa");finish(item,current,answer.feedback(),CrossSectorTaskRequest.Status.REJECTED);inboxService.completeObject(city(current),"cross_sector_task_request",item.getId());inboxService.notifyRequestResult(item,"recusada");return response(item);}
 private void finish(CrossSectorTaskRequest item,Employee employee,String feedback,CrossSectorTaskRequest.Status status){item.setStatus(status);item.setAnsweredBy(employee);item.setFeedback(feedback==null?"":feedback.trim());item.setAnsweredAt(LocalDateTime.now());repository.save(item);}
 private CrossSectorTaskRequest pending(UUID id,Employee employee){CrossSectorTaskRequest item=repository.findByIdAndCityHall_Id(id,city(employee)).orElseThrow(()->new ResourceNotFoundException("Demanda nao encontrada"));if(item.getStatus()!=CrossSectorTaskRequest.Status.PENDING)throw new BusinessException("A demanda ja foi respondida");return item;}
 private void requireDestination(CrossSectorTaskRequest item,Employee employee){if(!Roles.ADMIN.equals(employee.getRole())&&!item.getDestinationSector().getId().equals(sector(employee).getId()))throw new UnauthorizedException("Somente o setor de destino pode responder");}
 private Employee require(Employee employee){if(employee==null)throw new UnauthorizedException("E necessario estar autenticado");city(employee);return employee;}private UUID city(Employee employee){if(employee.getCityHallId()==null)throw new BusinessException("Usuario sem prefeitura");return employee.getCityHallId().getId();}private Sector sector(Employee employee){if(employee.getSectorId()==null)throw new BusinessException("Usuario sem setor");return employee.getSectorId();}
 private Response response(CrossSectorTaskRequest item){return new Response(item.getId(),item.getOriginSector().getId(),item.getOriginSector().getName(),item.getDestinationSector().getId(),item.getDestinationSector().getName(),item.getTitle(),item.getDescription(),item.getPriority(),item.getDeadline(),item.getStatus(),item.getRequestedBy().getFullName(),item.getAnsweredBy()==null?null:item.getAnsweredBy().getFullName(),item.getFeedback(),item.getGeneratedTask()==null?null:item.getGeneratedTask().getId(),item.getCreatedAt(),item.getAnsweredAt());}
}
