spring:
  jpa:
    show-sql: true
  application:
    name: HackGov

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret}
      expiration: ${JWT_TIME:2}

logging:
  level:
    root: INFO

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:test@gmail.com}
    password: ${MAIL_PASSWORD:testpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
    root: INFO